env:
  browser: true
  es2021: true
extends: 
  - airbnb-base
  - prettier
plugins: prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  prettier/prettier: error
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]